'use strict';

// Auto-register all built-in inspectors
require('./runtime');
require('./framework');
require('./http-tracker');
require('./system');
require('./active-handles');
require('./v8-heap');
require('./modules');
require('./process');
require('./database');
require('./redis');
require('./express');
require('./fastify');
require('./mongoose');
require('./bullmq');
require('./cluster');
require('./logging');
require('./cache');
require('./http-client');
require('./fd');
require('./metrics');
require('./perf');
require('./sockets');
require('./streams');
require('./security');
require('./health');
require('./scheduler');
require('./error-tracking');
require('./websocket');
require('./locks');
require('./migrations');
require('./config');
require('./feature-flags');
require('./endpoint-test');
require('./pool');
